# Generated by Django 5.2.1 on 2025-05-23 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbCarros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('especificacao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_carros',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbDisciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=255)),
                ('carga', models.IntegerField()),
                ('semestre', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_disciplinas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbEnderecos',
            fields=[
                ('cep', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'tb_enderecos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbAlunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracao.tbcarros')),
                ('cep', models.ForeignKey(blank=True, db_column='cep', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracao.tbenderecos')),
            ],
            options={
                'db_table': 'tb_alunos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracao.tbalunos')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracao.tbdisciplinas')),
            ],
            options={
                'db_table': 'tb_notas',
                'managed': True,
            },
        ),
    ]
